// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://asmppxzbbuicmezojuvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzbXBweHpiYnVpY21lem9qdXZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0MDAwNTMsImV4cCI6MjA4Nzk3NjA1M30.JHPKhAuEpUXmhHHkGjxytfCKgCspS4N54ErRbl3k4cM";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);